a = int(input('Digite um número inteiro para ver sua tabuada:'))
print('============')
print('{} X  1 = {}'.format(a, (a*1)))
print('{} X  2 = {}'.format(a, (a*2)))
print('{} X {:2} = {}'.format(a, 3, (a*3)))
print('{} X  {} = {}'.format(a, 4, (a*4)))
print('{} X  5 = {}'.format(a, (a*5)))
print('{} X  6 = {}'.format(a, (a*6)))
print('{} X  7 = {}'.format(a, (a*7)))
print('{} X  8 = {}'.format(a, (a*8)))
print('{} X  9 = {}'.format(a, (a*9)))
print('{} X 10 = {}'.format(a, (a*10)))
print('=' * 12)